### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by thedeadkoiclub** [nboldi/haskell-tools-atom#31]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [haskell-tools](https://github.com/nboldi/haskell-tools-atom) package 0.7.0

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:313

Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:392:9)
    at Object.start (/packages/haskell-tools/lib/server-manager.coffee:53:24)
    at /packages/haskell-tools/lib/server-manager.coffee:18:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -5:31.9.0 core:confirm (input.hidden-input)
     -5:29.2.0 core:backspace (input.hidden-input)
  2x -5:26.6.0 core:confirm (input.hidden-input)
     -0:40.2.0 core:paste (input.hidden-input)
     -0:10.3.0 haskell-tools:start-server (div.package-detail.panels-item)
```

### Non-Core Packages

```
atom-fix-path 0.1.0 
autocomplete-haskell 0.7.2 
build-stack 0.3.2 
haskell-debug 0.2.2 
haskell-ghc-mod 1.19.9 
haskell-grammar 0.4.0 
haskell-pointfree 0.2.0 
haskell-tools 0.7.0 
haskell-unicode-snippets 0.1.1 
hasklig 0.4.0 
helium 0.6.1 
hover-tooltips-hdevtools 0.10.0 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.2 
ide-haskell-hasktags 0.0.11 
ide-haskell-profiteurjs 0.0.2 
ide-haskell-repl 0.6.0 
language-haskell 1.12.1 
language-haskell-scoped 0.0.4 
linter-hlint 1.0.1 
script 3.15.0 
term3 0.22.1 
```

**Comment by nboldi** [comment]
Please check if the location of the executable (Settings/Packages/haskell-tools/Daemon-path) is set to the correct executable (ht-daemon).
If this does not solve the issue, the problem might be related to permission settings. Please try running Atom in administrator mode or equivalent.

**Comment by CaninoDev** [comment]
One should never have to execute Atom as root or sudo user. Has this been resolved yet?

**Comment by nboldi** [comment]
@thedeadkoiclub, please check if these steps solved your issue.
By the way, OS X is not officially supported, but I'm interested in if it actually works.

**Comment by tkvogt** [comment]
I had the same error (Ubuntu 16.04). I tried `sudo atom` and setting file permissions at various places without success.
Then I changed the path. I first used
`/home/till/.stack/snapshots/x86_64-linux/lts-9.21/8.0.2/bin`
then tried
`/home/till/.stack/snapshots/x86_64-linux/lts-9.21/8.0.2/bin/ht-daemon`
Spawn EACCES is gone but now i get:
> Unfortunately the server crashed, restarting after 1 s.

**Comment by nboldi** [comment]
I think the correct path is `/home/till/.stack/snapshots/x86_64-linux/lts-9.21/8.0.2/bin/ht-daemon`, because it should contain the name of the executable file.
Could you send the me the log produced when the server crashed? You can access it at the developer tools (Ctrl+Shift+i).

**Comment by tkvogt** [comment]
The server crash disappeared with using the most recent stack nightly. I think the issue can be closed. Maybe one should add examples to the settings window or check if the path is a directory.
