### ISSUE TITLE
Uncaught TypeError: Cannot read property 'once' of null

### ISSUE THREAD

**Issue by etorreborre** [nboldi/haskell-tools-atom#33]
[Enter steps to reproduce:]

1. I tried to rename a function

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.1
**Thrown From**: [haskell-tools](https://github.com/nboldi/haskell-tools-atom) package 0.9.0

### Stack Trace

Uncaught TypeError: Cannot read property 'once' of null

```
At /Users/etorreborre/.atom/packages/haskell-tools/lib/server-manager.coffee:38

TypeError: Cannot read property 'once' of null
    at Object.restart (/packages/haskell-tools/lib/server-manager.coffee:38:13)
    at /packages/haskell-tools/lib/server-manager.coffee:26:43)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1338:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:31.1.0 haskell-tools:start-server (input.hidden-input)
  2x -1:03.8.0 haskell-tools:refactor:rename-definition (input.hidden-input)
     -0:38.2.0 application:new-file (ide-haskell-panel-items.native-key-bindings)
     -0:36.8.0 core:close (input.hidden-input)
  2x -0:35.7.0 ide-haskell:next-error (input.hidden-input)
     -0:25.9.0 haskell-tools:refactor:rename-definition (input.hidden-input)
  2x -0:22.1.0 core:backspace (input.hidden-input)
     -0:16.2.0 core:confirm (input.hidden-input)
     -0:08.3.0 haskell-tools:restart-server (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-haskell 1.0.1 
haskell-ghc-mod 2.1.0 
haskell-grammar 0.4.0 
haskell-hoogle 0.1.3 
haskell-tools 0.9.0 
ide-haskell 2.1.1 
ide-haskell-cabal 2.0.2 
ide-haskell-hoogle 0.1.0 
ide-haskell-repl 0.7.3 
language-haskell 1.14.1 
language-idris 0.4.10 
language-pony 0.3.8 
print-atom 0.1.1 
term3 0.22.1 
```

**Comment by nboldi** [comment]
Thank you for submitting this issue. I will check it in a few days.

**Comment by etorreborre** [comment]
Closing this old issue now.
