### ISSUE TITLE
Uncaught TypeError: Bad argument

### ISSUE THREAD

**Issue by tcraigchilds** [nboldi/haskell-tools-atom#43]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Ubuntu 17.10
**Thrown From**: [haskell-tools](https://github.com/nboldi/haskell-tools-atom) package 1.1.0

### Stack Trace

Uncaught TypeError: Bad argument

```
At internal/child_process.js:289

TypeError: Bad argument
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at Object.exports.spawn (child_process.js:399:9)
    at Object.start (/packages/haskell-tools/lib/server-manager.coffee:69:24)
    at /packages/haskell-tools/lib/server-manager.coffee:20:41)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:18.6.0 haskell-tools:start-server (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.9 
atom-ctags 5.1.2 
atom-haskell 0.4.0 
atom-python-run 0.9.6 
atom-python-virtualenv 1.0.2 
autocomplete-haskell 1.0.1 
autocomplete-python 1.10.5 
autumn-highlighter-syntax 1.13.0 
build 0.70.0 
build-python 0.9.3 
build-stack 0.3.2 
busy-signal 1.4.3 
haskell-debug 0.3.5 
haskell-ghc-mod 2.2.2 
haskell-grammar 0.4.0 
haskell-hoogle 0.1.3 
haskell-pointfree 0.2.0 
haskell-scry 1.0.7 
haskell-tools 1.1.0 
haskell-unicode-snippets 0.1.1 
hasklig 0.4.0 
hover-tooltips-hdevtools 0.10.0 
ide-haskell 2.2.3 
ide-haskell-cabal 2.1.1 
ide-haskell-hasktags 0.0.13 
ide-haskell-hoogle 0.1.2 
ide-haskell-profiteurjs 0.1.0 
ide-haskell-repl 0.7.10 
ide-python 0.5.0 
intentions 1.1.5 
language-haskell 1.17.3 
language-haskell-scoped 0.1.0 
linter 2.2.0 
linter-ui-default 1.6.10 
python-debugger 0.2.0 
python-indent 1.1.4 
python-tools 0.6.9 
script 3.17.3 
```

**Comment by nboldi** [comment]
Hi! Thanks for reporting this issue. Could you copy the logs here? You can find them at the Console tab in the Developer Tools (View/Developer/Toggle Developer Tools). Look for the `Starting server with parameters:` line. Thank you!

**Comment by tcraigchilds** [comment]
<embedded>:121025 IntersectionObserver.observe(target): target element
is not a descendant of root.TreeView @ <embedded>:121025

Hope this helps.  This error happens when I open Atom.

Craig


On Sun, Jan 28, 2018, at 8:02 PM, Boldizsár Németh wrote:
> Hi! Thanks for reporting this issue. Could you copy the logs here? You
> can find them at the Console tab in the Developer Tools
> (View/Developer/Toggle Developer Tools). Look for the Starting server
> with parameters: line. Thank you!> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/nboldi/haskell-tools-atom/issues/43#issuecomment-361120285

**Comment by nboldi** [comment]
I think this warning is not related to the issue. Could you please attach the whole log after the error had happened?

**Comment by chriad** [comment]
I get the same error but I don't know what else to report then is already said above...
![refactor](https://user-images.githubusercontent.com/4353001/41600198-85a5a4de-73d5-11e8-8d3c-100b55ee8c48.png)

I don't find `Starting server with parameters:` in the console tab of the Developer Tools.

**Comment by nboldi** [comment]
I checked out, and the problem is probably that the path to the `ht-daemon` executable is not set up properly. Please go to Haskell/Settings and check the Daemon-path setting. If it is empty set to the path of the executable `/home/YOURUSERNAME/.cabal/bin/ht-daemon` if you installed Haskell-tools with cabal.

I will fix the issues with error reporting and automatic executable detection.
