### ISSUE TITLE
Cannot delete file

### ISSUE THREAD

**Issue by nboldi** [nboldi/haskell-tools-atom#6]
Deleting a file in the tree view causes the following problem:

```
TypeError: Cannot read property 'startsWith' of null
    at file:///C:/Users/nboldi/.atom/packages/haskell-tools/lib/client-manager.coffee:41:21
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\nboldi\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\nboldi\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\nboldi\AppData\Local\atom\app-1.14.0\resources\app.asar\src\command-registry.js:269:20)
    at CommandRegistry.handleCommandEvent (C:\Users\nboldi\AppData\Local\atom\app-1.14.0\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\nboldi\AppData\Local\atom\app-1.14.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\nboldi\AppData\Local\atom\app-1.14.0\resources\app.asar\src\atom-environment.js:1164:28)
    at EventEmitter.outerCallback (C:\Users\nboldi\AppData\Local\atom\app-1.14.0\resources\app.asar\src\application-delegate.js:333:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by nboldi** [comment]
Cannot reproduce
